services:

  rtsp_server:
    image: rtspserver
    build:
      context: .
      dockerfile: Dockerfile
    container_name: file_boardcaster
    ports:
      - "8553:8553"
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    environment:
      PYTHONPATH: /server
      GST_DEBUG: "3"
      VIDEO_WATCH_DIRS: /media
    volumes:
      - ./server/:/server/
      - ../media:/media:ro
    working_dir: /server
    entrypoint: ["python3", "main.py"]

    restart: unless-stopped

  transcoder:
    image: rtspserver
    build:
      context: .
      dockerfile: Dockerfile
    profiles: ["tools"]
    volumes:
      - ./server/:/server/:ro
      - ../media:/media
    working_dir: /server
    entrypoint: ["python3", "transcode.py"]
